<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="allegro_hand_left">
    <xacro:include filename="allegro_common.xacro" />

    <!-- THUMB MACRO -->
    <xacro:macro name="thumb_left"
                 params="prefix finger_num offset_origin_x offset_origin_y offset_origin_z finger_angle_r finger_angle_p finger_angle_y">

        <!-- [LINK 12] -->
        <link name="${prefix}link_${finger_num*4+0}">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_12.0_left.STL"/>
                </geometry>
                <material name="black">
                    <color rgba=".2 .2 .2 1"/>
                </material>
                <origin rpy="${180*DEG2RAD} 0 0" xyz="0 0 0"/>
            </visual>

            <collision>
                <geometry>
                    <box size="${link0_t_x} ${link0_t_y} ${link0_t_z}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="${-0.0358/2+0.0} ${-.018/2} ${.029/2}"/>
            </collision>

            <inertial>
              <mass value="0.0176" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="1.89273333333e-5" ixy="7.16716e-06" ixz="5.35568e-06"
                       iyy="1.43008213333e-05" iyz="6.8068e-06"
                       izz="1.89273333333e-05" />
            </inertial>
        </link>

        <joint name="${prefix}joint_${finger_num*4+0}" type="revolute">
            <axis xyz="+1 0 0"/>
            <limit effort="15" velocity="7"
                   lower="${limit_0_t_low-joint_safety_margin}"
                   upper="${limit_0_t_up-joint_safety_margin}"/>
            <parent link="${prefix}palm_link"/>
            <child link="${prefix}link_${finger_num*4+0}"/>
            <origin rpy="${finger_angle_r} ${finger_angle_p} ${finger_angle_y}"
                    xyz="${offset_origin_x} ${offset_origin_y} ${offset_origin_z}"/>
            <dynamics damping="3" friction="10"/>
        </joint>

        <!-- [LINK 13] -->
        <link name="${prefix}link_${finger_num*4+1}">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_13.0.STL"/>
                </geometry>
                <material name="black">
                    <color rgba=".2 .2 .2 1"/>
                </material>
            </visual>

            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link1_t_z}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${link1_t_z/2}"/>
            </collision>

            <inertial>
              <mass value="0.0119" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="4.24250866667e-06" ixy="1.032087e-06" ixz="1.603525e-06"
                       iyy="4.52362633333e-06" iyz="1.44808125e-06"
                       izz="4.24250866667e-06" />
            </inertial>
        </link>

        <joint name="${prefix}joint_${finger_num*4+1}" type="revolute">
            <axis xyz="0 0 -1"/>
            <limit effort="15" velocity="7"
                   lower="${limit_1_t_low+joint_safety_margin}"
                   upper="${limit_1_t_up-joint_safety_margin}"/>
            <parent link="${prefix}link_${finger_num*4+0}"/>
            <child link="${prefix}link_${finger_num*4+1}"/>
            <origin xyz="-0.027 -0.005 0.0399"/>
            <dynamics damping="3" friction="5"/>
        </joint>

        <!-- [LINK 14] -->
        <link name="${prefix}link_${finger_num*4+2}">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_14.0.STL"/>
                </geometry>
                <material name="black">
                </material>
            </visual>

            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link2_t_z}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${link2_t_z/2}"/>
            </collision>

            <inertial>
              <mass value="0.038" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="4.30439933333e-05" ixy="9.57068e-06" ixz="5.1205e-06" iyy="1.44451933333e-05"
                       iyz="1.342825e-05" izz="4.30439933333e-05" />
            </inertial>
        </link>

        <joint name="${prefix}joint_${finger_num*4+2}" type="revolute">
            <axis xyz="0 1 0"/>
            <limit effort="15" velocity="7"
                   lower="${limit_2_t_low+joint_safety_margin}"
                   upper="${limit_2_t_up-joint_safety_margin}"/>
            <parent link="${prefix}link_${finger_num*4+1}"/>
            <child link="${prefix}link_${finger_num*4+2}"/>
            <origin xyz="0 0 ${link1_t_z}"/>
            <dynamics damping="3" friction="10"/>
        </joint>

        <!-- [LINK 15] -->
        <link name="${prefix}link_${finger_num*4+3}">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_15.0.STL"/>
                </geometry>
                <material name="black">
                </material>
            </visual>

            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link3_t_z-fingerTip_r}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${(link3_t_z-fingerTip_r)/2}"/>
            </collision>

            <inertial>
              <mass value="0.0388" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="3.29223173333e-05" ixy="8.042076e-06" ixz="5.2283e-06"
                       iyy="1.47493026667e-5" iyz="1.1283525e-5"
                       izz="3.29223173333e-05" />
            </inertial>
        </link>

        <joint name="${prefix}joint_${finger_num*4+3}" type="revolute">
            <axis xyz="0 1 0"/>
            <limit effort="15" velocity="7"
                   lower="${limit_3_t_low+joint_safety_margin}"
                   upper="${limit_3_t_up-joint_safety_margin}"/>
            <parent link="${prefix}link_${finger_num*4+2}"/>
            <child link="${prefix}link_${finger_num*4+3}"/>
            <origin xyz="0 0 ${link2_t_z}"/>
            <dynamics damping="3" friction="12"/>
        </joint>

    </xacro:macro>
    <!-- END THUMB MACRO -->

    <!-- PALM MACRO-->
    <xacro:macro name="palm_left" params="prefix">
        <link name="${prefix}palm_link">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/base_link_left.STL"/>
                </geometry>
                <origin rpy="${-90*DEG2RAD} 0 0" xyz="0 0 0 "/>
                <material name="black">
                    <color rgba="0.2 0.2 0.2 1"/>
                </material>
            </visual>

            <collision>
                <origin rpy="0 0 0" xyz="-0.009300 0 -${palm_link_z/2}"/>
                <geometry>
                    <box size="0.0408 0.1130 ${palm_link_z}"/>
                </geometry>
            </collision>
            <inertial>
            <origin xyz="0 0 ${palm_link_z/2}" rpy="0 0 0"/>
            <mass value="0.4154"/>
            <inertia
                ixx="1e-4" ixy="0.0" ixz="0.0"
                iyy="1e-4" iyz="0.0"
                izz="1e-4"/>
            </inertial>
        </link>
    </xacro:macro>

    <!-- LEFT HAND MACRO -->
    <!-- FINGERS -->
    <!-- RIGHT HAND due to which finger is number 0 -->
    <!-- for LEFT HAND switch the sign of the **offset_origin_y** and **finger_angle_r** parameters-->
    <xacro:macro name="allegro_hand_left" params="prefix">
        <xacro:finger
            prefix="${prefix}"
            finger_num="0"
            offset_origin_x="${offset_origin_x_const}"
            offset_origin_y="-${offset_origin_y_const}"
            offset_origin_z="${offset_origin_z_const}"
            finger_angle_r="${5.0*DEG2RAD}"
            />
        <xacro:finger
            prefix="${prefix}"
            finger_num="1"
            offset_origin_x="${offset_origin_x_const}"
            offset_origin_y="0"
            offset_origin_z="${offset_origin_z_mid_const}"
            finger_angle_r="0.0"
            />
        <xacro:finger
            prefix="${prefix}"
            finger_num="2"
            offset_origin_x="${offset_origin_x_const}"
            offset_origin_y="${offset_origin_y_const}"
            offset_origin_z="${offset_origin_z_const}"
            finger_angle_r="-${5.0*DEG2RAD}"
            />
        <!-- THUMB -->
        <xacro:thumb_left
            prefix="${prefix}"
            finger_num="3"
            offset_origin_x="-0.0182"
            offset_origin_y="-0.019333"
            offset_origin_z="-0.045987"
            finger_angle_r="0"
            finger_angle_p="-${95*DEG2RAD}"
            finger_angle_y="${90*DEG2RAD}"
            />
        <xacro:palm_left
            prefix="${prefix}"
            />
    </xacro:macro>
</robot>
