<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:macro name="allegro_hand_fingertip" params="prefix finger_num origin*">
        <link name="${prefix}link_${finger_num*4+3}_tip">
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/link_15.0_tip.STL"/>
                </geometry>

                <material name="white">
                    <color rgba=".9 .9 .9 1"/>
                </material>
            </visual>

            <collision>
                <geometry>
                    <sphere radius="${fingerTip_r}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>

            <inertial>
              <mass value="0.0168" />
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <inertia ixx="9.68e-07" ixy="0" ixz="0"
                       iyy="9.68e-07" iyz="0"
                       izz="9.68e-07" />
            </inertial>
        </link>

        <joint name="${prefix}joint_${finger_num*4+3}_tip" type="fixed">
            <parent link="${prefix}link_${finger_num*4+3}"/>
            <child link="${prefix}link_${finger_num*4+3}_tip"/>
            <origin rpy="0 0 0" xyz="0 0 ${link3_t_z-fingerTip_r}"/>
        </joint>
    </xacro:macro>
</robot>